apiVersion: v1
kind: Pod
metadata:
  name: nginx-persistent 
spec:
  containers:
  - name: nginx-persistent
    image: nginx
    securityContext:
      privileged: true 
    volumeMounts:
    - mountPath: /config 
      name: hostpath-privileged
  securityContext: {}
  volumes:
    - name: hostpath-privileged
      persistentVolumeClaim:
        claimName: pvc-volume 


#kubectl apply -f 3-deployment.yaml  --namespace=foo