apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

  #kubectl apply -f 3-pvc.yaml  --namespace=foo

  #next is 3-deployment.yaml